default: &default
    # adapter: mysql2
    # encoding: utf8mb4
    # charset: utf8mb4
    # collation: utf8mb4_unicode_ci
    adapter: sqlite3
    encoding: utf8
    charset: utf8
    # collation: utf8mb4_unicode_ci


development:
  <<: *default
  database: verby

test:
  <<: *default
  database: verby

production:
  <<: *default
  database: verby
          
